### ISSUE TITLE
Querry: OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by MajliTech** [LiveOverflow/minecraft-hacked#1]
Auth failed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]

**Comment by FriwiDev** [comment]
Disable online mode

**Comment by LiveOverflow** [comment]
Since I started working on the videos the Mojang account migration has begun. Moving away from Mojang accounts to Microsoft accounts. This could cause some issues, but most likely the error you encountered is due to not using the proxy in offline mode (connecting to an offline server)

**Comment by fizzrepo** [comment]
This issue is to do with Windows support in quarry or one of it's dependencies. Someone managed to fix it by installing the windows subsystem for Linux, but I ran it in a docker environment on my Ubuntu VPS and it worked well.

**Comment by LawlessCS** [comment]
i managed to get it to work by chaning the QuietDownstreamFactory in the main python file to contain more information about the proxy server. Specifically, adding this line
online_mode = False

**Comment by LawlessCS** [comment]
Obviously I don't have write access to this repo, but I can confirm that making the change shown in the screenshot allows this to work on a local hosted server
![image](https://user-images.githubusercontent.com/37148937/162013857-5b7f5efe-5fd5-4b2c-a2c6-16f5ac03f7e8.png)
