### ISSUE TITLE
Fabric or Forge?

### ISSUE THREAD

**Issue by solonovamax** [LiveOverflow/minecraft-hacked#2]
For episodes 2 through 4, it is not stated whether Fabric of Forge will be used. (I HIGHLY recommend fabric over forge, if you haven't already made a decision on which to use)

I would recommend adding which mod loader is being used to the top of the README, as it changes a few things.

**Comment by LiveOverflow** [comment]
Those episodes are already recorded :) I'm using fabric

**Comment by anstropleuton** [comment]
@LiveOverflow what mods were you using?

**Comment by anstropleuton** [comment]
I was wondering how did you got the lightings like this:
![image](https://github.com/LiveOverflow/minecraft-hacked/assets/121956207/e93b25a9-0ee4-461a-a409-b4c605de0350)
