### ISSUE TITLE
I think this is a joke

### ISSUE THREAD

**Issue by h57758** [LiveOverflow/minecraft-hacked#3]
As of writing the day is April the 2nd.

I spotted herobrine in the video at about 6:17.

Please tell me if it was a April fools joke

**Comment by h57758** [comment]
Am i supposed to take that as a yes or no?

**Comment by TypicalFin** [comment]
i don't think he would put this much effort into making a video series and then disappointing everyone by revealing that it's fake

_... or would he?_

**Comment by h57758** [comment]
I’m so sorry I didn’t think about that.

But then why did I spot herobrine who doesn’t exist in normal minecraft? 🤔

**Comment by TypicalFin** [comment]
Probably just an easter egg. I doubt it's a joke, but there's a chance it is

**Comment by h57758** [comment]
I saw herobrine again! At 7:07

**Comment by robigan** [comment]
> I saw herobrine again! At 7:07

would you mind explaining where exactly?

**Comment by h57758** [comment]
In a tree

**Comment by robigan** [comment]
> In a tree at 7:07 of the original video

He also appears at the end of the second video as the one who trapped him in the bedrock house

**Comment by h57758** [comment]
> > In a tree at 7:07 of the original video
> 
> He also appears at the end of the second video as the one who trapped him in the bedrock house

`print(”That’s really intresting!”)`
