### ISSUE TITLE
getting same error when joining

### ISSUE THREAD

**Issue by fanda857** [LiveOverflow/minecraft-hacked#5]
Auth failed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]

**Comment by fanda857** [comment]
@LiveOverflow

**Comment by LiveOverflow** [comment]
See https://github.com/LiveOverflow/minecraft-hacked/issues/1#issuecomment-1086949921
